#!/usr/bin/env sh
# Multiplatform support? In this economy?

trap '' INT
trapped() (
    trap - INT
    export JAVA_HOME=/usr/lib/jvm/java-8-openjdk
    rm -r ./build/*
    /opt/gradle/gradle-4.10.3/bin/gradle build --stacktrace
    /opt/gradle/gradle-4.10.3/bin/gradle run --stacktrace
)

trapped
pkill -f "java.*-Xms20000m.*gradle"
pkill -f "java.*reactor_simulator"
/opt/gradle/gradle-4.10.3/bin/gradle --stop
echo "Killed goofball gradle daemon"
